# TODO file name == pipeline name (/azp run android-grpc-client-tests ?)
#
# TODO description + instructions
#
# We run this pipeline on a schedule and also developers can run it
# via /azp run command on PRs.
#
# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger: none

schedules:
  - cron: "0 9,21 * * *" # run at 9:00 and 21:00 (UTC) which is 1:00 and 13:00 (PST).
    displayName: grpc-dotnet Android client test schedule
    branches:
      include:
      - main
    always: true # the test is independent of the changes to the main branch since the client code is in another repo

# TODO do we need those variables?
# variables:
#   - template: /eng/pipelines/common/variables.yml

jobs:

# TODO we basically need to:
#
# 1) cd src/tests/src/tests/FunctionalTests/Android/Device_Emulator/gRPC/grpc-dotnet
# 2) docker build -t grpc-server -f testassets/InteropTestsWebsite .
# 3) docker run --name grpc-server -d -p 50052:50052 -p 80:80 grpc-server
# 4) adb reverse tcp:50052 tcp:50052; adb reverse tcp:80 tcp:80
# 5) dotnet build -t:Run -p:Configuration=Release ../Android.Device_Emulator.gRPC.Test.csproj
# 6) ... expect the result to be 42
# 7) docker stop grpc-server (if we care)
#
# so... 1-4) are helix pre-scripts, 5) is the main command, 7) is helix post-script?

#
# Android devices
# Build the whole product using Mono and run libraries tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    # TODO which job template?
    # jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: mono
    platforms:
    # - Android_arm TODO do we need/want it?
    - Android_arm64
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_Mono # TODO ???
      # we don't want to build the whole .net
      # buildArgs: -s mono+libs+host+packs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true $(_runSmokeTestsOnlyArg) /p:EnableAdditionalTimezoneChecks=true
      timeoutInMinutes: 180
      # extra steps, run tests
      extraStepsTemplate: /eng/pipelines/libraries/helix.yml
      extraStepsParameters:
        creator: dotnet-bot
        testRunNamePrefixSuffix: Mono_$(_BuildConfig)

# TODO Android_x64, Android_x86 - do those queues have docker?